/* create table to hold all users. */
CREATE TABLE garden_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_modified TIMESTAMPTZ
);

/* create foreign key relation between garden_users and journal entry table via user/author id. */
ALTER TABLE rose_entries 
    ADD COLUMN
        author_id INTEGER REFERENCES garden_users(id) ON DELETE CASCADE; 